# Generated by Django 2.0.5 on 2019-01-14 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_obj', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='action',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
