# Generated by Django 2.0.5 on 2019-01-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20190111_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tags_helper',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='tweets.Tag'),
        ),
    ]
