# Generated by Django 2.0.5 on 2019-01-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20190111_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retweet',
            name='user',
        ),
    ]
