# Generated by Django 2.0.5 on 2019-01-12 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0006_remove_retweet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='retweet',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='retweets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
