# Generated by Django 2.0.5 on 2019-01-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_retweet_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retweet',
            options={},
        ),
        migrations.RenameField(
            model_name='retweet',
            old_name='time',
            new_name='pub_date',
        ),
        migrations.AddField(
            model_name='retweet',
            name='is_retweet',
            field=models.BooleanField(default=True),
        ),
    ]
