# Generated by Django 2.0.5 on 2019-01-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_auto_20190114_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='username',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
    ]
